### ISSUE TITLE
make haaska.zip fail

### ISSUE THREAD

**Issue by master-kenobi** [mike-grant/haaska#13]
I'm stuck at `make` command. so far, these are the steps i took...

1. sudo apt-get install git zip python-pip
2. git clone https://github.com/mike-grant/haaska.git
3. cd haaska/config
4. mv config.json.sample config.json
5. sudo nano config.json
6. key in the URL and password
7. cd ..
8. make

it gives this error...

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
Makefile:10: recipe for target 'haaska.zip' failed
make: *** [haaska.zip] Error 2
```

please advice. thanks.

**Comment by eXtatic-GitHub** [comment]
tried sudo make?

**Comment by master-kenobi** [comment]
@eXtatic-GitHub thanks. it works! sorry for noob question.
