### ISSUE TITLE
503 Server Error: Service Temporarily Unavailable for url

### ISSUE THREAD

**Issue by dangizzi** [mike-grant/haaska#195]
I have been having this issue with a previously working integration.  I have completely started from the beginning and continue to have the following issue.  config.yaml is setup and when I navigate to https://myurl.com/api/alexa/smart_home I receive 405: Method Not Allowed

Reverse proxy is setup and ports are open and no issue navigating to my https://myurl.com/ for HA

Here's my output log:
Response:
{
  "errorMessage": "503 Server Error: Service Temporarily Unavailable for url: https://myurl.com/api/alexa/smart_home",
  "errorType": "HTTPError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      111,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True)"
    ],
    [
      "/var/task/haaska.py",
      66,
      "post",
      "r.raise_for_status()"
    ],
    [
      "/var/task/requests/models.py",
      940,
      "raise_for_status",
      "raise HTTPError(http_error_msg, response=self)"
    ]
  ]
}

Request ID:
"cc1208e5-07dc-4e0c-80ff-f59e82923168"

Function logs:
START RequestId: cc1208e5-07dc-4e0c-80ff-f59e82923168 Version: $LATEST
[DEBUG]	2020-12-15T18:00:47.669Z	cc1208e5-07dc-4e0c-80ff-f59e82923168	calling alexa/smart_home with {'directive': {'header': {'namespace': 'Alexa.Discovery', 'name': 'Discover', 'payloadVersion': '3', 'messageId': '1bd5d003-31b9-476f-ad03-71d471922820'}, 'payload': {'scope': {'type': 'BearerToken', 'token': 'access-token-from-skill'}}}}
[DEBUG]	2020-12-15T18:00:47.690Z	cc1208e5-07dc-4e0c-80ff-f59e82923168	Starting new HTTPS connection (1): myurl.com:443
[DEBUG]	2020-12-15T18:00:47.920Z	cc1208e5-07dc-4e0c-80ff-f59e82923168	https://myurl.com:443 "POST /api/alexa/smart_home HTTP/1.1" 503 None
503 Server Error: Service Temporarily Unavailable for url: https://myurl.com/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 111, in event_handler
    return ha.post('alexa/smart_home', event, wait=True)
  File "/var/task/haaska.py", line 66, in post
    r.raise_for_status()
  File "/var/task/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://myurl.com/api/alexa/smart_home

END RequestId: cc1208e5-07dc-4e0c-80ff-f59e82923168
REPORT RequestId: cc1208e5-07dc-4e0c-80ff-f59e82923168	Duration: 314.93 ms	Billed Duration: 315 ms	Memory Size: 128 MB	Max Memory Used: 53 MB	Init Duration: 315.73 ms

**Comment by dangizzi** [comment]
Bot fighter is stopping the request on the firewall.  I will close this request.
