### ISSUE TITLE
Domain name change issue

### ISSUE THREAD

**Issue by TheDarthFather** [mike-grant/haaska#232]
Later edit .. amazing coincidence ... my IPS moved me to IPV6 in the same day ... closing this one and opening a new IPV6 one

Hello.
I just changed my home domain. 
I changed as well ha domain with the reverse proxy and works fine in browser.

I changed the config in the haska function and I get this error:
MySubDomain below is actualy my subdomain without **.com** .. I assume is intended !?
Any hints ?

```
START RequestId: ba09f356-0360-4f5f-afd7-2b8aeb2ae523 Version: $LATEST
20 Dec 2021 18:31:39,100 [INFO] (/var/runtime/bootstrap.py) main started at epoch 1640025099100
20 Dec 2021 18:31:39,308 [INFO] (/var/runtime/bootstrap.py) init complete at epoch 1640025099309
HTTPSConnectionPool(host='MySubDomain', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcce3eca128>: Failed to establish a new connection: [Errno -2] Name or service not known',)): ConnectionError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 112, in event_handler
    return ha.post('alexa/smart_home', event, wait=True)
  File "/var/task/haaska.py", line 66, in post
    timeout=(None, read_timeout))
  File "/var/task/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/task/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='MySubDomain', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcce3eca128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Later Edit:** 
Even more strange .. sometime after, I started to get this error instead.
Also I tried to re-enable my skill on Alexa and is failing .. :(

```
Test Event Name
TestHaaska

Response
{
  "errorMessage": "2021-12-20T21:14:42.221Z 3918aa5f-9b24-48c2-9084-bdfa6a8d0f66 Task timed out after 3.00 seconds"
}

Function Logs
START RequestId: 3918aa5f-9b24-48c2-9084-bdfa6a8d0f66 Version: $LATEST
20 Dec 2021 21:14:38,939 [INFO] (/var/runtime/bootstrap.py) main started at epoch 1640034878939
20 Dec 2021 21:14:39,214 [INFO] (/var/runtime/bootstrap.py) init complete at epoch 1640034879215
END RequestId: 3918aa5f-9b24-48c2-9084-bdfa6a8d0f66
REPORT RequestId: 3918aa5f-9b24-48c2-9084-bdfa6a8d0f66	Duration: 3003.70 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 51 MB	Init Duration: 466.57 ms	
2021-12-20T21:14:42.221Z 3918aa5f-9b24-48c2-9084-bdfa6a8d0f66 Task timed out after 3.00 seconds

Request ID
3918aa5f-9b24-48c2-9084-bdfa6a8d0f66
```

**Comment by TheDarthFather** [comment]
IPV6 issue
