### ISSUE TITLE
core-2022.2.6

### ISSUE THREAD

**Issue by thierry-rhone** [mike-grant/haaska#236]
Hi,
I am on home assistant supervised
new core breaks haaska connexion. (It goes  back to normal if I restore to core-2021.12.10.

Lamda Function error
```
HTTPSConnectionPool(host='xxxxxx.duckdns.org', port=8123): Max retries exceeded with url: /api/alexa/smart_home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f34652bc748>: Failed to establish a new connection: [Errno 111] Connection refused',)): ConnectionError
Traceback (most recent call last):
File "/var/task/haaska.py", line 111, in event_handler
return ha.post('alexa/smart_home', event, wait=True)
File "/var/task/haaska.py", line 65, in post
timeout=(None, read_timeout))
File "/var/task/requests/sessions.py", line 581, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/var/task/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/var/task/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/var/task/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xxxxxx.duckdns.org', port=8123): Max retries exceeded with url: /api/alexa/smart_home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f34652bc748>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by thierry-rhone** [comment]
Reinstalled and ok
