### ISSUE TITLE
help with Haaska integration

### ISSUE THREAD

**Issue by tekstein** [mike-grant/haaska#240]
Hello, 

I need some help on why I get the message below. When I run the test after setting up the haaska integration. I've double check the token and it's correct. Is there something else I'm missing in HA. Thanks again for the help. 

est Event Name
haaska

Response
{
  "errorMessage": "401 Client Error: Unauthorized for url: https://steinsmarthome.duckdns.org/api/alexa/smart_home",
  "errorType": "HTTPError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      111,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True)"
    ],
    [
      "/var/task/haaska.py",
      66,
      "post",
      "r.raise_for_status()"
    ],
    [
      "/var/task/requests/models.py",
      940,
      "raise_for_status",
      "raise HTTPError(http_error_msg, response=self)"
    ]
  ]
}

Function Logs
START RequestId: e3aefd06-e525-415a-8de3-42c8f2a43a76 Version: $LATEST
401 Client Error: Unauthorized for url: https://steinsmarthome.duckdns.org/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 111, in event_handler
    return ha.post('alexa/smart_home', event, wait=True)
  File "/var/task/haaska.py", line 66, in post
    r.raise_for_status()
  File "/var/task/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://steinsmarthome.duckdns.org/api/alexa/smart_home

END RequestId: e3aefd06-e525-415a-8de3-42c8f2a43a76
REPORT RequestId: e3aefd06-e525-415a-8de3-42c8f2a43a76	Duration: 400.70 ms	Billed Duration: 401 ms	Memory Size: 128 MB	Max Memory Used: 51 MB	Init Duration: 427.77 ms

Request ID
e3aefd06-e525-415a-8de3-42c8f2a43a76

**Comment by inverse** [comment]
Are you able to curl locally with the token? Def sounds like something is up with the token
