### ISSUE TITLE
Lambda Test Failed

### ISSUE THREAD

**Issue by WhiteNoseThunderPants** [mike-grant/haaska#41]
So I am having an issue that I have not seen mentioned yet when testing my Lambda function.

I am getting the following errors from Amazon:

**This is the result:**

```
 {
   "errorMessage": "401 Client Error: Unauthorized for url: https://{Public_URL}/api/alexa/smart_home",
   "errorType": "HTTPError",
   "stackTrace": [
     [
       "/var/task/haaska.py",
       108,
       "event_handler",
       "return ha.post('alexa/smart_home', event, wait=True).json()"
     ],
     [
       "/var/task/haaska.py",
       62,
       "post",
       "r.raise_for_status()"
     ],
     [
       "/var/task/requests/models.py",
       939,
       "raise_for_status",
       "raise HTTPError(http_error_msg, response=self)"
     ]
   ]
 }
```

**This is the Amazon log output:**

```
START RequestId: 077120e9-9039-11e8-83f3-a15fbdabfa96 Version: $LATEST
401 Client Error: Unauthorized for url: https://{PUBLIC_URL/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 108, in event_handler
    return ha.post('alexa/smart_home', event, wait=True).json()
  File "/var/task/haaska.py", line 62, in post
    r.raise_for_status()
  File "/var/task/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://{PUBLIC_URL}/api/alexa/smart_home
 
END RequestId: 077120e9-9039-11e8-83f3-a15fbdabfa96
REPORT RequestId: 077120e9-9039-11e8-83f3-a15fbdabfa96	Duration: 549.55 ms	Billed Duration: 600 ms 	Memory Size: 128 MB	Max Memory Used: 31 MB	
```

**This is the relevant Home Assistant log:**

```
2018-07-25 13:24:27 WARNING (MainThread) [homeassistant.components.http.auth] Please change to use bearer token access /api/alexa/smart_home

2018-07-25 13:24:27 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 54.152.59.58

2018-07-25 13:24:27 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=Login attempt failed, message=Login attempt or request with invalid authentication from 54.152.59.58, notification_id=http-login, service_call_id=23219184785616-9>
 
2018-07-25 13:24:27 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.httplogin, old_state=<state persistent_notification.httplogin=notifying; title=Login attempt failed, message=Login attempt or request with invalid authentication from 12.52.94.170 @ 2018-07-25T13:24:18.459097-05:00>, new_state=<state persistent_notification.httplogin=notifying; title=Login attempt failed, message=Login attempt or request with invalid authentication from 54.152.59.58 @ 2018-07-25T13:24:18.459097-05:00
```

**This is the code in my test event:**
```
{
  "directive": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover",
      "payloadVersion": "3",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
    },
    "payload": {
      "scope": {
        "type": "BearerToken",
        "token": "access-token-from-skill"
     }
    }
  }
}
```

I am using the new auth system in HA, if that makes a difference. I also do have my API password set and verified it matched what the config.json had before compiling and uploading.

I need some guidance on where to go from here.

EDIT: Forgot to add that I am on the latest 0.74.1 version of HA.

**Comment by anthonylavado** [comment]
@WhiteNoseThunderPants Hi there, looks like this might have to do with the recent auth changes. Have a look at this and let me know if it’s relevant: 
https://community.home-assistant.io/t/0-74-tuya-cloudflare-dns-push-camera-and-users-ui/60562/64

**Comment by anthonylavado** [comment]
@mike-grant If auth is changing, we’ll need to figure out what we can do to tackle it going forward

**Comment by WhiteNoseThunderPants** [comment]
@anthonylavado Thank you so much, that worked! Now I just have to look into why no devices are being discovered. I remember seeing something about that, just have to find it.

**Comment by beloso** [comment]
Is there a fix for version 0.75.3?

I am getting the same error. But adding the legacy auth provider is not working :/

**Comment by WhiteNoseThunderPants** [comment]
@beloso, I'm on 0.75.3 and it is still working fine for me. I did not have to make any other changes.

**Comment by beloso** [comment]
I got it to work, it was an issue between the keyboard and the chair (it was my fault)

**Comment by WhiteNoseThunderPants** [comment]
@beloso, gladd you got it working! I have had plenty of those problems.

**Comment by MisterCommand** [comment]
Hi, It is not working for me, I am in version 0.79.3.
Is there a fix?

**Comment by beloso** [comment]
My issue was related, to the scripts I believe. I did got it working. I just don't remember how I did it :D
