### ISSUE TITLE
405: Method Not Allowed

### ISSUE THREAD

**Issue by ikifar2012** [mike-grant/haaska#57]
I'm getting this error ``405: Method Not Allowed`` when testing my skill
```
405 Client Error: Method Not Allowed for url: https://ha.domain.ca/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 109, in event_handler
    return ha.post('alexa/smart_home', event, wait=True).json()
  File "/var/task/haaska.py", line 63, in post
    r.raise_for_status()
  File "/var/task/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://ha.domain.ca/api/alexa/smart_home
```
i'm using a long lived token

**Comment by thizzle** [comment]
I experienced this issue as well. For me, it was because my `config.json` has an HTTP URL to my home-assistant instance. When an HTTP `POST` request is issued to the HTTP URL by the Python HTTP client, it is redirected to the HTTPS URL by nginx. When the HTTP client follows the redirect, it changes the request method from `POST` to `GET`, which is not an an allowed method for this endpoint.

Make sure you've specified an HTTPS URL in your `config.json` file.

**Comment by anthonylavado** [comment]
@ikifar2012 Just to follow up here - have you tried the Lambda test to see if it's working now?

**Comment by ikifar2012** [comment]
I got it working now it just is not finding one of my scripts here is the configuration.yaml 
```yaml
alexa:
  smart_home:
    filter:
      include_entities:
        - script.going_to_bed
      include_domains:
        - switch
      exclude_entities:
        - switch.tv_samsung
```

**Comment by anthonylavado** [comment]
@ikifar2012 - Thanks for posting that. So it’s not finding the script Going To Bed? It should look like a switch in Alexa.

**Comment by ikifar2012** [comment]
It just started working I don't get why it wasn't before
