### ISSUE TITLE
Update Home Assistant 0.85.1

### ISSUE THREAD

**Issue by ruben0909** [mike-grant/haaska#88]
Hi
1. Update Home Assistant to 0.85.1 .
2. Forget All devicesin http://alexa.amazon.com
3. Discover Devices in Alexa stopped not work.
4. I Check in AWS Console
When I test the function
https://github.com/mike-grant/haaska/wiki/Testing-Haaska
In AWS console I get is error
`{
  "errorMessage": "404 Client Error: Not Found for url: https://xxx.myqnapcloud.com:8443/api/alexa/smart_home",
  "errorType": "HTTPError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      109,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True).json()"
    ],
    [
      "/var/task/haaska.py",
      63,
      "post",
      "r.raise_for_status()"
    ],
    [
      "/var/task/requests/models.py",
      940,
      "raise_for_status",
      "raise HTTPError(http_error_msg, response=self)"
    ]
  ]
}`

`START RequestId: 5fa0a7b6-9487-4903-b80d-dd86aed16cda Version: $LATEST
404 Client Error: Not Found for url: https://xxx.myqnapcloud.com:8443/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 109, in event_handler
    return ha.post('alexa/smart_home', event, wait=True).json()
  File "/var/task/haaska.py", line 63, in post
    r.raise_for_status()
  File "/var/task/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://misol.myqnapcloud.com:8443/api/alexa/smart_home`

Thank you

**Comment by ruben0909** [comment]
I don`t know what was happennig with this but is working now.
Thank you
